//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SecondIINoneMC.Web.Data.Entities;

namespace SecondIINoneMC.Web.Data.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIINMCDataEntitiesContext : DbContext
    {
        public SIINMCDataEntitiesContext()
            : base("name=SIINMCDataEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Charter> Charters { get; set; }
        public DbSet<Guestbook> Guestbooks { get; set; }
        public DbSet<OfficerPosition> OfficerPositions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
