//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondIINoneMC.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charter
    {
        public Charter()
        {
            this.Guestbooks = new HashSet<Guestbook>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Notes { get; set; }
        public string FacebookId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string EmailAddress { get; set; }
        public string FacebookName { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Guestbook> Guestbooks { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
